#!/usr/bin/env ruby
# encoding: utf-8

# Add the `profile` directory to the load path.
$:.push File.expand_path("../../profile", __FILE__)

require 'xe'
require 'xe/benchmark'
require 'xe/profiler'

Xe::Profiler.()
